"""add file_count to ingestion_runs

Revision ID: 52217c8d714d
Revises: a72468b1c116
Create Date: 2026-01-21 16:53:23.644285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52217c8d714d'
down_revision: Union[str, Sequence[str], None] = 'a72468b1c116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('file_count', sa.Integer(), nullable=True), schema='audit_testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'file_count', schema='audit_testing')
    # ### end Alembic commands ###
