"""initial audit schema

Revision ID: 870d62ff301e
Revises: 
Create Date: 2026-01-20 18:25:47.417775

"""
from config.config import settings


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

AUDIT_SCHEMA = settings.AUDIT_SCHEMA
# revision identifiers, used by Alembic.
revision: str = '870d62ff301e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_runs',
    sa.Column('dq_run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.Text(), nullable=False),
    sa.Column('suite_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('STARTED','PASSED','FAILED')", name='chk_dq_runs_status'),
    sa.PrimaryKeyConstraint('dq_run_id'),
    schema=AUDIT_SCHEMA
    )
    op.create_index('idx_dq_runs_dataset_time', 'dq_runs', ['dataset_name', sa.literal_column('started_at DESC')], unique=False, schema='audit_testing')
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('ingest_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('s3_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('STARTED','SUCCEEDED','FAILED')", name='chk_ingestion_runs_status'),
    sa.PrimaryKeyConstraint('run_id'),
    schema=AUDIT_SCHEMA
    )
    op.create_index('idx_ingestion_runs_source_date', 'ingestion_runs', ['source_name', 'ingest_date'], unique=False, schema='audit_testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ingestion_runs_source_date', table_name='ingestion_runs', schema=AUDIT_SCHEMA)
    op.drop_table('ingestion_runs', schema=AUDIT_SCHEMA)
    op.drop_index('idx_dq_runs_dataset_time', table_name='dq_runs', schema=AUDIT_SCHEMA)
    op.drop_table('dq_runs', schema=AUDIT_SCHEMA)
    # ### end Alembic commands ###
