"""add run_duration_seconds to dq_runs

Revision ID: a72468b1c116
Revises: 870d62ff301e
Create Date: 2026-01-20 19:16:06.649150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from config.config import settings
AUDIT_SCHEMA = settings.AUDIT_SCHEMA


# revision identifiers, used by Alembic.
revision: str = 'a72468b1c116'
down_revision: Union[str, Sequence[str], None] = '870d62ff301e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dq_runs', sa.Column('run_duration_seconds', sa.Integer(), nullable=True), schema=AUDIT_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dq_runs', 'run_duration_seconds', schema=AUDIT_SCHEMA)
    # ### end Alembic commands ###
