"""add_total_bytes_to_ingestion_runs

Revision ID: b4299d897051
Revises: 8aa6a32eb5f5
Create Date: 2026-01-28 11:35:39.510083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4299d897051'
down_revision: Union[str, Sequence[str], None] = '8aa6a32eb5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('total_bytes', sa.BigInteger(), nullable=True), schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'total_bytes', schema='audit')
    # ### end Alembic commands ###
