# ==============================================================================
# envs/dev/rds-postgres/secrets.tf
# ==============================================================================
#
# Purpose
# - Store dev Postgres credentials in AWS Secrets Manager.
#
# Notes
# - The password is generated by Terraform and stored only in Secrets Manager.
# - No secrets are committed to the repository.
# ==============================================================================

resource "random_password" "db_master" {
  length  = 32
  special = true
}

resource "aws_secretsmanager_secret" "db_master" {
  name = "${var.project_name}/${var.environment}/rds-postgres/master"

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-postgres-master"
  }
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  #
  # Note: This uses the RDS module outputs (endpoint/port/db_name), so it stays
  # environment-driven and avoids hardcoding.
  secret_string = jsonencode({
    engine   = "postgres"
    host     = module.rds_postgres.endpoint
    port     = module.rds_postgres.port
    dbname   = module.rds_postgres.db_name
    username = var.db_username
    password = random_password.db_master.result
  })
}




# ------------------------------------------------------------------------------
# Convenience secret: POSTGRES_DSN (what the app expects)
# ------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "postgres_dsn" {
  name        = "${var.project_name}/${var.environment}/postgres_dsn"
  description = "Application DSN for the audit Postgres database."

  tags = {
    Name = "${var.project_name}-${var.environment}-postgres-dsn"
  }
}

resource "aws_secretsmanager_secret_version" "postgres_dsn" {
  secret_id = aws_secretsmanager_secret.postgres_dsn.id

  secret_string = format(
    "postgresql://%s:%s@%s:%s/%s",
    var.db_username,
    random_password.db_master.result,
    module.rds_postgres.endpoint,
    module.rds_postgres.port,
    module.rds_postgres.db_name
  )
}
